sets.exported={
    main={ name="Malevolence", augments={'INT+10','Mag. Acc.+10','"Mag.Atk.Bns."+10','"Fast Cast"+5',}},
    sub={ name="Malevolence", augments={'INT+1','Mag. Acc.+1','"Mag.Atk.Bns."+5',}},
    range={ name="Doomsday", augments={'"Mag.Atk.Bns."+15','"Store TP"+5',}},
    ammo="Ra'Kaznar Bullet",
    head={ name="Dampening Tam", augments={'DEX+9','Accuracy+13','Mag. Acc.+14','Quadruple Attack +2',}},
    body={ name="Rawhide Vest", augments={'HP+50','"Subtle Blow"+7','"Triple Atk."+2',}},
    hands={ name="Leyline Gloves", augments={'Accuracy+15','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+3',}},
    legs={ name="Taeon Tights", augments={'Accuracy+23','"Triple Atk."+2','STR+6',}},
    feet={ name="Herculean Boots", augments={'Accuracy+25','"Dual Wield"+3','MND+3','Attack+5',}},
    neck="Iqabi Necklace",
    waist="Hurch'lan Sash",
    left_ear="Steelflash Earring",
    right_ear="Heartseeker Earring",
    left_ring="Etana Ring",
    right_ring="Rajas Ring",
    back="Kayapa Cape",
}