sets.exported={
    main={ name="Malevolence", augments={'INT+10','Mag. Acc.+10','"Mag.Atk.Bns."+10','"Fast Cast"+5',}},
    sub={ name="Malevolence", augments={'INT+1','Mag. Acc.+1','"Mag.Atk.Bns."+5',}},
    range={ name="Doomsday", augments={'"Mag.Atk.Bns."+15','"Store TP"+5',}},
    ammo="Ra'Kaznar Bullet",
    head={ name="Dampening Tam", augments={'DEX+9','Accuracy+13','Mag. Acc.+14','Quadruple Attack +2',}},
    body={ name="Pursuer's Doublet", augments={'DEX+7','AGI+10','"Recycle"+15',}},
    hands={ name="Leyline Gloves", augments={'Accuracy+15','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+3',}},
    legs={ name="Herculean Trousers", augments={'Accuracy+26','"Store TP"+4','DEX+10','Attack+4',}},
    feet={ name="Herculean Boots", augments={'Rng.Acc.+30','Crit. hit damage +4%','Rng.Atk.+10',}},
    neck="Iqabi Necklace",
    waist="Scout's Belt",
    left_ear="Clearview Earring",
    right_ear="Volley Earring",
    left_ring="Cacoethic Ring",
    right_ring="Paqichikaji Ring",
    back="Libeccio Mantle",
}